=== jeanbsrl/Projet_TechnoXML_TUX_Letter_Game/src/xml/profil.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema  version="1.0"
            targetNamespace="http://myGame/tux"
            xmlns:tux="http://myGame/tux"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xs:include schemaLocation="dico.xsd"/>
    
    <xs:element name="profil" type="tux:Profil"/>
    
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="avatar" type="tux:image_avatar"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="tux:Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="image_avatar">
        <xs:restriction base="xs:string">
            <xs:pattern value=".+\.(jpg|png|jpeg|gif)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="tux:Partie" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" type="xs:double" minOccurs="0"/>
            <xs:element name="mot" type="tux:Mot"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
        <xs:attribute name="trouvÃ©" type="tux:taux_reussite"/>
    </xs:complexType>
    
    <xs:simpleType name="taux_reussite">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}\%"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== jeanbsrl/Projet_TechnoXML_TUX_Letter_Game/src/xml/profil_Justin.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profil xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux profil.xsd">
    <nom>Justin</nom>
    <avatar>sasuke.jpg</avatar>
    <anniversaire>1999-06-17</anniversaire>
    <parties>
        <partie date="2021-12-14" trouvé="66%">
            <mot niveau="3">convexité</mot>
        </partie>
        <partie date="2021-12-14" trouvé="0%">
            <mot niveau="3">convexité</mot>
        </partie>
    <partie date="2021-12-14" trouvé="25%">
            <mot niveau="4">escalier</mot>
        </partie>
    <partie date="2021-12-14" trouvé="0%">
            <mot niveau="1">sept</mot>
        </partie>
        <partie date="2021-12-14">
            <temps>7</temps>
            <mot niveau="1">sept</mot>
        </partie>
    <partie date="2021-12-14">
            <temps>12</temps>
            <mot niveau="3">attendrir</mot>
        </partie>
    </parties>
</profil>

=== jeanbsrl/Projet_TechnoXML_TUX_Letter_Game/src/xml/profil_Tom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profil xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux profil.xsd">
    <nom>Tom</nom>
    <avatar>naruto.jpg</avatar>
    <anniversaire>1997-12-21</anniversaire>
    <parties>
        <partie date="2021-12-14">
            <temps>8</temps>
            <mot niveau="2">marron</mot>
        </partie>
        <partie date="2021-12-14">
            <temps>16</temps>
            <mot niveau="5">entracte</mot>
        </partie>
    <partie date="2021-12-14">
            <temps>4</temps>
            <mot niveau="1">café</mot>
        </partie>
    <partie date="2021-12-14">
            <temps>9</temps>
            <mot niveau="2">profil</mot>
        </partie>
    <partie date="2021-12-14">
            <temps>15</temps>
            <mot niveau="4">grand-mère</mot>
        </partie>
    </parties>
</profil>
